services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/app
    working_dir: /var/www/app
    depends_on:
      - azurite
  
  nginx:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/app:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
        
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - '10000:10000'
    volumes:
      - azurite-data:/data

volumes:
  azurite-data:
