services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/app
    working_dir: /var/www/app
  
  nginx:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/app:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
